twig:
  default_path: "%kernel.project_dir%/templates"
  globals:
    app_name: "SkillHarbor"
    app_tagline: "Learn deeply. Grow visibly."
  form_themes:
    - "forms/admin_form_theme.html.twig"
<<<<<<< HEAD

=======
    - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
>>>>>>> 496c29c (Integrating Rich Text Editor)
when@test:
  twig:
    strict_variables: true
