# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    lesson_upload_base: "%kernel.project_dir%/public/uploads/lessons"
    lesson_upload_public_base: "/uploads/lessons"
    exam_docx_upload_dir: '%kernel.project_dir%/public/uploads/docx'
    exam_pdf_upload_dir: '%kernel.project_dir%/public/uploads/pdf'

    # ✅ Windows (change si ton chemin diffère)
    libreoffice_soffice_path: 'C:\Program Files\LibreOffice\program\soffice.exe'

    openai_api_key: '%env(OPENAI_API_KEY)%'

    plagiarismsearch_api_key: '%env(PLAGIARISMSEARCH_API_KEY)%'
    plagiarismsearch_endpoint: '%env(resolve:PLAGIARISMSEARCH_ENDPOINT)%'

    # ✅ GROQ (AJOUT)
    groq_api_key: '%env(GROQ_API_KEY)%'
    groq_model: '%env(GROQ_MODEL)%'
    

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # ✅ OpenAiQuizGenerator (FINAL ✅)
    App\Service\OpenAiQuizGenerator:
        arguments:
            $openAiApiKey: '%env(OPENAI_API_KEY)%'

    # ✅ GroqAiClient (AJOUT)
    App\Service\GroqAiClient:
        arguments:
            $apiKey: '%groq_api_key%'
            $model: '%groq_model%'