parameters:
    lesson_upload_base: "%kernel.project_dir%/public/uploads/lessons"
    lesson_upload_public_base: "/uploads/lessons"
    huggingface_api_key: '%env(HUGGINGFACE_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ModerationService:
        arguments:
            $huggingFaceApiKey: '%huggingface_api_key%'