<?php

namespace App\DataFixtures;

/**
 * SampleData - Hardcoded sample datasets for SkillHarbor
 * No database required - all data stored as PHP arrays
 */
class SampleData
{
    public static function getCategories(): array
    {
        return [
            ['id' => 1, 'name' => 'Development', 'slug' => 'development', 'icon' => 'code', 'count' => 1240],
            ['id' => 2, 'name' => 'Business', 'slug' => 'business', 'icon' => 'briefcase', 'count' => 890],
            ['id' => 3, 'name' => 'Data Science', 'slug' => 'data-science', 'icon' => 'chart', 'count' => 654],
            ['id' => 4, 'name' => 'Design', 'slug' => 'design', 'icon' => 'palette', 'count' => 532],
            ['id' => 5, 'name' => 'Marketing', 'slug' => 'marketing', 'icon' => 'megaphone', 'count' => 421],
            ['id' => 6, 'name' => 'Personal Development', 'slug' => 'personal-development', 'icon' => 'user', 'count' => 378],
            ['id' => 7, 'name' => 'IT & Software', 'slug' => 'it-software', 'icon' => 'server', 'count' => 756],
            ['id' => 8, 'name' => 'Photography', 'slug' => 'photography', 'icon' => 'camera', 'count' => 234],
        ];
    }

    public static function getInstructors(): array
    {
        return [
            [
                'id' => 1,
                'name' => 'Dr. Sarah Chen',
                'slug' => 'sarah-chen',
                'avatar' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
                'title' => 'Senior Machine Learning Engineer',
                'company' => 'Google AI',
                'bio' => 'Dr. Sarah Chen is a leading expert in machine learning with over 15 years of experience. She has published numerous papers on neural networks and deep learning architectures.',
                'expertise' => ['Machine Learning', 'Python', 'TensorFlow', 'Deep Learning'],
                'rating' => 4.9,
                'reviews_count' => 12450,
                'students_count' => 185000,
                'courses_count' => 8,
                'social' => ['twitter' => '@sarahchen_ai', 'linkedin' => 'sarahchen'],
                'verified' => true,
            ],
            [
                'id' => 2,
                'name' => 'Marcus Johnson',
                'slug' => 'marcus-johnson',
                'avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
                'title' => 'Full Stack Developer & Educator',
                'company' => 'TechMentor',
                'bio' => 'Marcus is passionate about making web development accessible to everyone. With 12 years of industry experience at companies like Spotify and Stripe.',
                'expertise' => ['JavaScript', 'React', 'Node.js', 'TypeScript'],
                'rating' => 4.8,
                'reviews_count' => 8920,
                'students_count' => 142000,
                'courses_count' => 12,
                'social' => ['twitter' => '@marcusdev', 'github' => 'marcusj'],
                'verified' => true,
            ],
            [
                'id' => 3,
                'name' => 'Elena Rodriguez',
                'slug' => 'elena-rodriguez',
                'avatar' => 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
                'title' => 'UX Design Lead',
                'company' => 'Figma',
                'bio' => 'Elena has been designing digital products for over a decade. She leads the UX team at Figma and is passionate about design systems.',
                'expertise' => ['UI/UX Design', 'Figma', 'Design Systems', 'User Research'],
                'rating' => 4.9,
                'reviews_count' => 6780,
                'students_count' => 98000,
                'courses_count' => 6,
                'social' => ['dribbble' => 'elenarodriguez'],
                'verified' => true,
            ],
            [
                'id' => 4,
                'name' => 'James Mitchell',
                'slug' => 'james-mitchell',
                'avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
                'title' => 'Data Scientist & Author',
                'company' => 'DataCamp',
                'bio' => 'James is a bestselling author and data scientist. He specializes in making complex statistical concepts accessible.',
                'expertise' => ['Data Analysis', 'R', 'Statistics', 'SQL'],
                'rating' => 4.7,
                'reviews_count' => 5430,
                'students_count' => 76000,
                'courses_count' => 9,
                'social' => ['twitter' => '@jamesmitchell'],
                'verified' => true,
            ],
            [
                'id' => 5,
                'name' => 'Aisha Patel',
                'slug' => 'aisha-patel',
                'avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop',
                'title' => 'Product Manager & Strategist',
                'company' => 'Meta',
                'bio' => 'Aisha has launched products used by millions. She teaches practical product management skills based on real-world experience.',
                'expertise' => ['Product Management', 'Strategy', 'Agile', 'User Stories'],
                'rating' => 4.8,
                'reviews_count' => 4210,
                'students_count' => 54000,
                'courses_count' => 5,
                'social' => ['linkedin' => 'aishapatel'],
                'verified' => true,
            ],
            [
                'id' => 6,
                'name' => 'David Kim',
                'slug' => 'david-kim',
                'avatar' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
                'title' => 'Cloud Architect',
                'company' => 'AWS',
                'bio' => 'David is an AWS Hero and cloud computing expert. He helps organizations modernize their infrastructure.',
                'expertise' => ['AWS', 'Cloud Architecture', 'DevOps', 'Kubernetes'],
                'rating' => 4.9,
                'reviews_count' => 7650,
                'students_count' => 112000,
                'courses_count' => 7,
                'social' => ['twitter' => '@davidkim_cloud'],
                'verified' => true,
            ],
            [
                'id' => 7,
                'name' => 'Lisa Thompson',
                'slug' => 'lisa-thompson',
                'avatar' => 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
                'title' => 'Digital Marketing Expert',
                'company' => 'HubSpot',
                'bio' => 'Lisa is a certified digital marketing expert with a track record of growing startups from zero to millions in revenue.',
                'expertise' => ['SEO', 'Content Marketing', 'Analytics', 'Growth Hacking'],
                'rating' => 4.6,
                'reviews_count' => 3890,
                'students_count' => 67000,
                'courses_count' => 6,
                'social' => ['twitter' => '@lisathompson'],
                'verified' => false,
            ],
            [
                'id' => 8,
                'name' => 'Robert Chen',
                'slug' => 'robert-chen',
                'avatar' => 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop',
                'title' => 'Cybersecurity Specialist',
                'company' => 'CrowdStrike',
                'bio' => 'Robert is a certified ethical hacker with experience protecting Fortune 500 companies from cyber threats.',
                'expertise' => ['Cybersecurity', 'Ethical Hacking', 'Network Security', 'Penetration Testing'],
                'rating' => 4.8,
                'reviews_count' => 5120,
                'students_count' => 89000,
                'courses_count' => 5,
                'social' => ['twitter' => '@robchen_sec'],
                'verified' => true,
            ],
        ];
    }

    public static function getCourses(): array
    {
        return [
            [
                'id' => 1,
                'title' => 'Complete Machine Learning & Data Science Bootcamp',
                'slug' => 'machine-learning-data-science-bootcamp',
                'subtitle' => 'Learn Data Science, Data Analysis, Machine Learning and Python with real-world projects',
                'thumbnail' => 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=450&fit=crop',
                'instructor_id' => 1,
                'category_id' => 3,
                'level' => 'Intermediate',
                'language' => 'English',
                'duration_hours' => 42,
                'lessons_count' => 385,
                'rating' => 4.9,
                'reviews_count' => 12450,
                'students_count' => 185000,
                'price' => 89.99,
                'original_price' => 199.99,
                'is_bestseller' => true,
                'is_featured' => true,
                'updated_at' => '2024-01-15',
                'skills' => ['Python', 'TensorFlow', 'Pandas', 'Scikit-learn', 'Neural Networks'],
                'what_you_learn' => [
                    'Build powerful machine learning models from scratch',
                    'Master Python for data science and machine learning',
                    'Implement deep learning algorithms with TensorFlow',
                    'Create real-world portfolio projects',
                    'Understand the mathematics behind algorithms',
                ],
                'requirements' => [
                    'Basic programming knowledge (any language)',
                    'High school level mathematics',
                    'A computer with internet access',
                ],
                'description' => 'This comprehensive bootcamp takes you from complete beginner to job-ready data scientist. You\'ll learn everything from Python basics to advanced machine learning algorithms.',
            ],
            [
                'id' => 2,
                'title' => 'Modern React with Redux & TypeScript',
                'slug' => 'modern-react-redux-typescript',
                'subtitle' => 'Build scalable, production-ready React applications with modern tools',
                'thumbnail' => 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=450&fit=crop',
                'instructor_id' => 2,
                'category_id' => 1,
                'level' => 'Intermediate',
                'language' => 'English',
                'duration_hours' => 36,
                'lessons_count' => 290,
                'rating' => 4.8,
                'reviews_count' => 8920,
                'students_count' => 142000,
                'price' => 79.99,
                'original_price' => 149.99,
                'is_bestseller' => true,
                'is_featured' => true,
                'updated_at' => '2024-01-20',
                'skills' => ['React', 'Redux', 'TypeScript', 'Next.js', 'Testing'],
                'what_you_learn' => [
                    'Master React 18 with hooks and modern patterns',
                    'Build type-safe applications with TypeScript',
                    'Manage complex state with Redux Toolkit',
                    'Deploy production apps with Vercel/AWS',
                ],
                'requirements' => [
                    'Basic JavaScript knowledge',
                    'Familiarity with HTML/CSS',
                ],
                'description' => 'Learn React the modern way. This course covers everything from basic components to advanced patterns used by top tech companies.',
            ],
            [
                'id' => 3,
                'title' => 'UX/UI Design Masterclass: From Zero to Pro',
                'slug' => 'ux-ui-design-masterclass',
                'subtitle' => 'Learn user experience and interface design with Figma and real client projects',
                'thumbnail' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=450&fit=crop',
                'instructor_id' => 3,
                'category_id' => 4,
                'level' => 'Beginner',
                'language' => 'English',
                'duration_hours' => 28,
                'lessons_count' => 195,
                'rating' => 4.9,
                'reviews_count' => 6780,
                'students_count' => 98000,
                'price' => 69.99,
                'original_price' => 129.99,
                'is_bestseller' => false,
                'is_featured' => true,
                'updated_at' => '2024-01-18',
                'skills' => ['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Design Systems'],
                'what_you_learn' => [
                    'Create stunning user interfaces from scratch',
                    'Conduct effective user research',
                    'Build and maintain design systems',
                    'Create interactive prototypes',
                ],
                'requirements' => [
                    'No prior design experience needed',
                    'Access to Figma (free)',
                ],
                'description' => 'Transform your design skills with this comprehensive masterclass. Learn the same techniques used by designers at top tech companies.',
            ],
            [
                'id' => 4,
                'title' => 'AWS Certified Solutions Architect',
                'slug' => 'aws-solutions-architect',
                'subtitle' => 'Pass the AWS exam and master cloud architecture',
                'thumbnail' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=450&fit=crop',
                'instructor_id' => 6,
                'category_id' => 7,
                'level' => 'Intermediate',
                'language' => 'English',
                'duration_hours' => 45,
                'lessons_count' => 320,
                'rating' => 4.9,
                'reviews_count' => 7650,
                'students_count' => 112000,
                'price' => 99.99,
                'original_price' => 199.99,
                'is_bestseller' => true,
                'is_featured' => false,
                'updated_at' => '2024-01-22',
                'skills' => ['AWS', 'EC2', 'S3', 'Lambda', 'CloudFormation'],
                'what_you_learn' => [
                    'Design resilient, high-performing architectures',
                    'Implement cost-optimized solutions',
                    'Pass the AWS Solutions Architect exam',
                ],
                'requirements' => ['Basic IT knowledge', 'Familiarity with Linux commands'],
                'description' => 'Get AWS certified and advance your career. This comprehensive course covers all exam objectives with hands-on labs.',
            ],
            [
                'id' => 5,
                'title' => 'Complete Python Developer Bootcamp',
                'slug' => 'python-developer-bootcamp',
                'subtitle' => 'Learn Python programming from scratch to advanced level',
                'thumbnail' => 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&h=450&fit=crop',
                'instructor_id' => 2,
                'category_id' => 1,
                'level' => 'Beginner',
                'language' => 'English',
                'duration_hours' => 52,
                'lessons_count' => 420,
                'rating' => 4.7,
                'reviews_count' => 15200,
                'students_count' => 234000,
                'price' => 74.99,
                'original_price' => 159.99,
                'is_bestseller' => true,
                'is_featured' => false,
                'updated_at' => '2024-01-10',
                'skills' => ['Python', 'Django', 'Flask', 'APIs', 'Automation'],
                'what_you_learn' => [
                    'Master Python programming fundamentals',
                    'Build web applications with Django',
                    'Automate repetitive tasks',
                    'Work with databases and APIs',
                ],
                'requirements' => ['No programming experience required', 'A computer with internet'],
                'description' => 'The most comprehensive Python course on the platform. Go from zero to Python hero.',
            ],
            [
                'id' => 6,
                'title' => 'Digital Marketing Masterclass',
                'slug' => 'digital-marketing-masterclass',
                'subtitle' => 'Complete guide to SEO, social media, and content marketing',
                'thumbnail' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
                'instructor_id' => 7,
                'category_id' => 5,
                'level' => 'Beginner',
                'language' => 'English',
                'duration_hours' => 24,
                'lessons_count' => 180,
                'rating' => 4.6,
                'reviews_count' => 3890,
                'students_count' => 67000,
                'price' => 59.99,
                'original_price' => 119.99,
                'is_bestseller' => false,
                'is_featured' => true,
                'updated_at' => '2024-01-05',
                'skills' => ['SEO', 'Google Analytics', 'Social Media', 'Content Strategy'],
                'what_you_learn' => [
                    'Create effective marketing strategies',
                    'Master SEO and content marketing',
                    'Run successful social media campaigns',
                ],
                'requirements' => ['No prior marketing experience'],
                'description' => 'Learn digital marketing from an industry expert. Build real campaigns from day one.',
            ],
            [
                'id' => 7,
                'title' => 'Ethical Hacking & Penetration Testing',
                'slug' => 'ethical-hacking-penetration-testing',
                'subtitle' => 'Learn cybersecurity and become a certified ethical hacker',
                'thumbnail' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=450&fit=crop',
                'instructor_id' => 8,
                'category_id' => 7,
                'level' => 'Intermediate',
                'language' => 'English',
                'duration_hours' => 38,
                'lessons_count' => 285,
                'rating' => 4.8,
                'reviews_count' => 5120,
                'students_count' => 89000,
                'price' => 84.99,
                'original_price' => 179.99,
                'is_bestseller' => false,
                'is_featured' => false,
                'updated_at' => '2024-01-12',
                'skills' => ['Penetration Testing', 'Kali Linux', 'Network Security', 'Metasploit'],
                'what_you_learn' => [
                    'Identify and exploit vulnerabilities',
                    'Conduct professional penetration tests',
                    'Secure networks and applications',
                ],
                'requirements' => ['Basic networking knowledge', 'Linux fundamentals'],
                'description' => 'Become an ethical hacker. Learn the same techniques used by security professionals worldwide.',
            ],
            [
                'id' => 8,
                'title' => 'Product Management Fundamentals',
                'slug' => 'product-management-fundamentals',
                'subtitle' => 'Learn to build and launch successful products',
                'thumbnail' => 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=450&fit=crop',
                'instructor_id' => 5,
                'category_id' => 2,
                'level' => 'Beginner',
                'language' => 'English',
                'duration_hours' => 18,
                'lessons_count' => 145,
                'rating' => 4.8,
                'reviews_count' => 4210,
                'students_count' => 54000,
                'price' => 64.99,
                'original_price' => 129.99,
                'is_bestseller' => false,
                'is_featured' => false,
                'updated_at' => '2024-01-08',
                'skills' => ['Product Strategy', 'Agile', 'User Stories', 'Roadmapping'],
                'what_you_learn' => [
                    'Define product vision and strategy',
                    'Work effectively with development teams',
                    'Prioritize features and manage backlogs',
                ],
                'requirements' => ['No prior PM experience required'],
                'description' => 'Learn product management from a Meta PM. Build your skills to land your dream PM role.',
            ],
            [
                'id' => 9,
                'title' => 'SQL for Data Analysis',
                'slug' => 'sql-data-analysis',
                'subtitle' => 'Master SQL queries for business intelligence and analytics',
                'thumbnail' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop',
                'instructor_id' => 4,
                'category_id' => 3,
                'level' => 'Beginner',
                'language' => 'English',
                'duration_hours' => 22,
                'lessons_count' => 165,
                'rating' => 4.7,
                'reviews_count' => 5430,
                'students_count' => 76000,
                'price' => 49.99,
                'original_price' => 99.99,
                'is_bestseller' => false,
                'is_featured' => false,
                'updated_at' => '2024-01-14',
                'skills' => ['SQL', 'PostgreSQL', 'Data Analysis', 'Reporting'],
                'what_you_learn' => [
                    'Write complex SQL queries',
                    'Analyze large datasets',
                    'Create reports and dashboards',
                ],
                'requirements' => ['No prior SQL experience'],
                'description' => 'The essential SQL course for data analysts. Learn to extract insights from data.',
            ],
            [
                'id' => 10,
                'title' => 'Node.js Microservices Architecture',
                'slug' => 'nodejs-microservices',
                'subtitle' => 'Build scalable backend systems with Node.js',
                'thumbnail' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=450&fit=crop',
                'instructor_id' => 2,
                'category_id' => 1,
                'level' => 'Advanced',
                'language' => 'English',
                'duration_hours' => 32,
                'lessons_count' => 240,
                'rating' => 4.8,
                'reviews_count' => 3240,
                'students_count' => 45000,
                'price' => 89.99,
                'original_price' => 179.99,
                'is_bestseller' => false,
                'is_featured' => false,
                'updated_at' => '2024-01-19',
                'skills' => ['Node.js', 'Microservices', 'Docker', 'Kubernetes', 'RabbitMQ'],
                'what_you_learn' => [
                    'Design microservices architectures',
                    'Implement service-to-service communication',
                    'Deploy with Docker and Kubernetes',
                ],
                'requirements' => ['Solid Node.js experience', 'Basic Docker knowledge'],
                'description' => 'Advanced course for experienced developers. Learn to build enterprise-grade systems.',
            ],
        ];
    }

    public static function getLessons(): array
    {
        return [
            // Machine Learning Course (Course 1)
            ['id' => 1, 'course_id' => 1, 'section_id' => 1, 'title' => 'Welcome to the Course', 'duration' => '5:30', 'is_preview' => true, 'order' => 1],
            ['id' => 2, 'course_id' => 1, 'section_id' => 1, 'title' => 'Course Overview & Roadmap', 'duration' => '12:45', 'is_preview' => true, 'order' => 2],
            ['id' => 3, 'course_id' => 1, 'section_id' => 1, 'title' => 'Setting Up Your Environment', 'duration' => '18:20', 'is_preview' => false, 'order' => 3],
            ['id' => 4, 'course_id' => 1, 'section_id' => 2, 'title' => 'Python Basics Refresher', 'duration' => '25:10', 'is_preview' => false, 'order' => 1],
            ['id' => 5, 'course_id' => 1, 'section_id' => 2, 'title' => 'Working with NumPy', 'duration' => '32:45', 'is_preview' => false, 'order' => 2],
            ['id' => 6, 'course_id' => 1, 'section_id' => 2, 'title' => 'Pandas for Data Manipulation', 'duration' => '45:30', 'is_preview' => false, 'order' => 3],
            ['id' => 7, 'course_id' => 1, 'section_id' => 3, 'title' => 'Introduction to Machine Learning', 'duration' => '28:15', 'is_preview' => true, 'order' => 1],
            ['id' => 8, 'course_id' => 1, 'section_id' => 3, 'title' => 'Supervised vs Unsupervised Learning', 'duration' => '22:40', 'is_preview' => false, 'order' => 2],
            ['id' => 9, 'course_id' => 1, 'section_id' => 3, 'title' => 'Linear Regression from Scratch', 'duration' => '38:55', 'is_preview' => false, 'order' => 3],
            ['id' => 10, 'course_id' => 1, 'section_id' => 3, 'title' => 'Logistic Regression Explained', 'duration' => '35:20', 'is_preview' => false, 'order' => 4],
            // React Course (Course 2)
            ['id' => 11, 'course_id' => 2, 'section_id' => 4, 'title' => 'Welcome & Course Goals', 'duration' => '8:15', 'is_preview' => true, 'order' => 1],
            ['id' => 12, 'course_id' => 2, 'section_id' => 4, 'title' => 'Modern JavaScript Essentials', 'duration' => '42:30', 'is_preview' => false, 'order' => 2],
            ['id' => 13, 'course_id' => 2, 'section_id' => 5, 'title' => 'React Fundamentals', 'duration' => '35:45', 'is_preview' => true, 'order' => 1],
            ['id' => 14, 'course_id' => 2, 'section_id' => 5, 'title' => 'Components & Props Deep Dive', 'duration' => '28:20', 'is_preview' => false, 'order' => 2],
            ['id' => 15, 'course_id' => 2, 'section_id' => 5, 'title' => 'State Management with useState', 'duration' => '32:10', 'is_preview' => false, 'order' => 3],
        ];
    }

    public static function getSections(): array
    {
        return [
            ['id' => 1, 'course_id' => 1, 'title' => 'Getting Started', 'order' => 1],
            ['id' => 2, 'course_id' => 1, 'title' => 'Python for Data Science', 'order' => 2],
            ['id' => 3, 'course_id' => 1, 'title' => 'Machine Learning Fundamentals', 'order' => 3],
            ['id' => 4, 'course_id' => 2, 'title' => 'Introduction', 'order' => 1],
            ['id' => 5, 'course_id' => 2, 'title' => 'React Core Concepts', 'order' => 2],
        ];
    }

    public static function getReviews(): array
    {
        return [
            ['id' => 1, 'course_id' => 1, 'user_name' => 'John D.', 'rating' => 5, 'title' => 'Best ML course I\'ve taken', 'content' => 'Dr. Chen explains complex concepts in a way that\'s easy to understand. The hands-on projects really helped cement my learning.', 'helpful_count' => 234, 'created_at' => '2024-01-10'],
            ['id' => 2, 'course_id' => 1, 'user_name' => 'Sarah M.', 'rating' => 5, 'title' => 'Comprehensive and practical', 'content' => 'I went from knowing nothing about ML to building my own models. The course structure is excellent.', 'helpful_count' => 189, 'created_at' => '2024-01-08'],
            ['id' => 3, 'course_id' => 1, 'user_name' => 'Michael R.', 'rating' => 4, 'title' => 'Great content, some pacing issues', 'content' => 'Overall excellent course. Some sections felt rushed while others could have been condensed.', 'helpful_count' => 87, 'created_at' => '2024-01-05'],
            ['id' => 4, 'course_id' => 2, 'user_name' => 'Emma W.', 'rating' => 5, 'title' => 'Finally understand React!', 'content' => 'Marcus is an amazing teacher. The TypeScript integration lessons were particularly helpful.', 'helpful_count' => 312, 'created_at' => '2024-01-15'],
            ['id' => 5, 'course_id' => 2, 'user_name' => 'David L.', 'rating' => 5, 'title' => 'Worth every penny', 'content' => 'The Redux Toolkit section alone is worth the price. Very up-to-date with latest React 18 features.', 'helpful_count' => 156, 'created_at' => '2024-01-12'],
        ];
    }

    public static function getBadges(): array
    {
        return [
            ['id' => 1, 'name' => 'First Steps', 'description' => 'Complete your first lesson', 'icon' => 'star', 'color' => 'harbor', 'xp' => 50],
            ['id' => 2, 'name' => 'Quick Learner', 'description' => 'Complete 10 lessons in one day', 'icon' => 'zap', 'color' => 'warning', 'xp' => 100],
            ['id' => 3, 'name' => 'Course Champion', 'description' => 'Complete your first course', 'icon' => 'trophy', 'color' => 'coral', 'xp' => 500],
            ['id' => 4, 'name' => 'Knowledge Seeker', 'description' => 'Enroll in 5 courses', 'icon' => 'book', 'color' => 'success', 'xp' => 200],
            ['id' => 5, 'name' => 'Perfect Score', 'description' => 'Score 100% on a quiz', 'icon' => 'check-circle', 'color' => 'success', 'xp' => 150],
            ['id' => 6, 'name' => 'Week Warrior', 'description' => 'Study 7 days in a row', 'icon' => 'flame', 'color' => 'coral', 'xp' => 300],
            ['id' => 7, 'name' => 'Community Helper', 'description' => 'Get 10 upvotes on your posts', 'icon' => 'heart', 'color' => 'danger', 'xp' => 250],
            ['id' => 8, 'name' => 'Note Taker', 'description' => 'Create 50 notes', 'icon' => 'edit', 'color' => 'harbor', 'xp' => 200],
        ];
    }

    public static function getLevels(): array
    {
        return [
            ['level' => 1, 'name' => 'Newcomer', 'min_xp' => 0, 'max_xp' => 500],
            ['level' => 2, 'name' => 'Learner', 'min_xp' => 500, 'max_xp' => 1500],
            ['level' => 3, 'name' => 'Explorer', 'min_xp' => 1500, 'max_xp' => 3500],
            ['level' => 4, 'name' => 'Scholar', 'min_xp' => 3500, 'max_xp' => 7000],
            ['level' => 5, 'name' => 'Expert', 'min_xp' => 7000, 'max_xp' => 12000],
            ['level' => 6, 'name' => 'Master', 'min_xp' => 12000, 'max_xp' => 20000],
            ['level' => 7, 'name' => 'Grandmaster', 'min_xp' => 20000, 'max_xp' => 35000],
            ['level' => 8, 'name' => 'Legend', 'min_xp' => 35000, 'max_xp' => null],
        ];
    }

    public static function getCommunityPosts(): array
    {
        return [
            ['id' => 1, 'title' => 'Tips for staying motivated during long courses?', 'content' => 'I\'m halfway through the ML bootcamp and finding it hard to stay motivated. Any tips from those who\'ve completed it?', 'author' => 'Alex K.', 'upvotes' => 234, 'comments_count' => 45, 'tag' => 'Discussion', 'created_at' => '2 hours ago'],
            ['id' => 2, 'title' => 'Just landed my first dev job thanks to this platform!', 'content' => 'After 6 months of learning React and TypeScript, I finally got an offer. Thank you SkillHarbor!', 'author' => 'Maria S.', 'upvotes' => 892, 'comments_count' => 127, 'tag' => 'Success Story', 'created_at' => '5 hours ago'],
            ['id' => 3, 'title' => 'Best practices for taking notes while learning?', 'content' => 'What note-taking strategies have worked best for you? I\'m trying to improve my retention.', 'author' => 'James L.', 'upvotes' => 156, 'comments_count' => 38, 'tag' => 'Discussion', 'created_at' => '8 hours ago'],
            ['id' => 4, 'title' => 'Study group for AWS certification?', 'content' => 'Looking to form a study group for the AWS Solutions Architect exam. Who\'s interested?', 'author' => 'Priya M.', 'upvotes' => 89, 'comments_count' => 23, 'tag' => 'Study Group', 'created_at' => '12 hours ago'],
            ['id' => 5, 'title' => 'How I built my portfolio project using skills from the Design course', 'content' => 'Sharing my journey of creating a full design system after completing Elena\'s UX course.', 'author' => 'Chris D.', 'upvotes' => 445, 'comments_count' => 67, 'tag' => 'Project Showcase', 'created_at' => '1 day ago'],
        ];
    }

    public static function getQuizzes(): array
    {
        return [
            ['id' => 1, 'course_id' => 1, 'title' => 'Python Fundamentals Quiz', 'questions_count' => 10, 'duration_minutes' => 15, 'passing_score' => 70],
            ['id' => 2, 'course_id' => 1, 'title' => 'Machine Learning Basics', 'questions_count' => 15, 'duration_minutes' => 25, 'passing_score' => 75],
            ['id' => 3, 'course_id' => 2, 'title' => 'React Components Quiz', 'questions_count' => 12, 'duration_minutes' => 20, 'passing_score' => 70],
            ['id' => 4, 'course_id' => 3, 'title' => 'UX Principles Assessment', 'questions_count' => 10, 'duration_minutes' => 15, 'passing_score' => 80],
        ];
    }

    public static function getCurrentUser(): array
    {
        return [
            'id' => 1,
            'name' => 'Alex Thompson',
            'email' => 'alex.thompson@email.com',
            'avatar' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop',
            'level' => 4,
            'level_name' => 'Scholar',
            'xp' => 4250,
            'xp_to_next_level' => 7000,
            'streak' => 12,
            'enrolled_courses' => [1, 2, 3],
            'completed_courses' => [3],
            'badges' => [1, 2, 3, 4, 6],
        ];
    }

    public static function getTestimonials(): array
    {
        return [
            [
                'name' => 'Jennifer Walsh',
                'role' => 'Software Engineer at Google',
                'avatar' => 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop',
                'content' => 'SkillHarbor helped me transition from marketing to tech. The structured learning paths and real-world projects made all the difference.',
            ],
            [
                'name' => 'Michael Chen',
                'role' => 'Data Scientist at Netflix',
                'avatar' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
                'content' => 'The machine learning courses here are top-notch. I learned more practical skills in 3 months than I did in my entire university program.',
            ],
            [
                'name' => 'Sophia Rodriguez',
                'role' => 'UX Designer at Airbnb',
                'avatar' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop',
                'content' => 'The design courses taught by industry professionals gave me the portfolio pieces I needed to land my dream job.',
            ],
        ];
    }
}
